# Generated by Django 4.2.7 on 2024-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('health_status', models.CharField(max_length=100)),
                ('lactation_stage', models.CharField(max_length=100)),
                ('reproductive_status', models.CharField(max_length=100)),
                ('milking_frequency', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nutrition_protein', models.IntegerField()),
                ('nutrition_carbohydrates', models.IntegerField()),
                ('nutrition_minerals', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('prev_milk_production', models.IntegerField()),
                ('predicted_milk_production', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CropPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('precipitation', models.IntegerField()),
                ('nitrogen_level', models.IntegerField()),
                ('phosphorus_level', models.IntegerField()),
                ('potassium_level', models.IntegerField()),
                ('ph_level', models.IntegerField()),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
    ]
